# Generated by Django 5.2.8 on 2025-11-06 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PU', 'Penalaran Umum'), ('PPU', 'Pengetahuan & Pemahaman Umum'), ('PBM', 'Pemahaman Bacaan & Menulis'), ('PK', 'Pengetahuan Kuantitatif'), ('LBI', 'Literasi Bahasa Indonesia'), ('LBE', 'Literasi Bahasa Inggris'), ('PM', 'Penalaran Matematika')], max_length=4, unique=True)),
                ('nama_subtest', models.CharField(max_length=100)),
                ('durasi_menit', models.DecimalField(decimal_places=1, max_digits=5)),
                ('jumlah_soal', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soal_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('option_e', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal', to='quiz.subtest')),
            ],
        ),
    ]
