# Generated by Django 5.2.8 on 2025-11-22 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilTryout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(help_text='ID batch tryout (mis. batch-1)', max_length=50)),
                ('jawaban', models.JSONField(default=dict, help_text='Dictionary: {soal_id: jawaban_user}')),
                ('jumlah_benar', models.PositiveIntegerField(default=0)),
                ('jumlah_salah', models.PositiveIntegerField(default=0)),
                ('jumlah_kosong', models.PositiveIntegerField(default=0)),
                ('skor', models.DecimalField(decimal_places=2, default=0.0, help_text='Skor dalam persentase (0-100)', max_digits=5)),
                ('waktu_mulai', models.DateTimeField(auto_now_add=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('durasi_detik', models.PositiveIntegerField(blank=True, help_text='Durasi pengerjaan dalam detik', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_tryout', to='quiz.subtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_tryout', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-waktu_selesai', '-created_at'],
                'unique_together': {('user', 'subtest', 'batch_id')},
            },
        ),
    ]
