# Generated by Django 5.2.8 on 2025-11-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_hasiltryout'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='soal_image',
            field=models.ImageField(blank=True, help_text='Gambar soal (jika soal dalam bentuk gambar)', null=True, upload_to='soal_images/%Y/%m/%d/'),
        ),
    ]
